[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/NexusFR/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
